---
# Stelt de tijdzone van een node in
- hosts: big-ben
  tasks:
  - name: Set timezone to Europe/Amsterdam.
    timezone:
      name: Europe/Amsterdam
    become: yes
    notify:
    - update tzdata

  - name: update tzdata
    command: dpkg-reconfigure --frontend noninteractive tzdata
