- include_tasks: remove_user.yml
  loop: "{{training_users}}"
  loop_control:
    loop_var: training_user
  tags:
    - users

- include_tasks: create_user.yml
  loop: "{{training_users}}"
  loop_control:
    loop_var: training_user
  tags:
    - users

- name: Install required software for the controller
  import_tasks: software.yml
  tags:
    - software

- include_tasks: sample_scripts.yml
  loop:
  - evert
  - pi
  loop_control:
    loop_var: training_user
  tags:
    - scripts
