# If the module encrypt_password_passlib is used the pip module passlib 
# must be installed that require python-setuptools python-pip
# For now use the encrypt_password module

# - name: Update apt packages
#   apt: 
#     update_cache: yes

# - name: Install a list of packages
#   apt:
#     name: "{{ packages }}"
#   vars:
#     packages:
#     - python-setuptools
#     - python-pip

# - name: Install passlib
#   pip:
#     name: passlib
- include_tasks: remove_user.yml
  loop: "{{training_users}}"
  loop_control:
    loop_var: training_user

- include_tasks: create_user.yml
  loop: "{{training_users}}"
  loop_control:
    loop_var: training_user